name: Playwright E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn clean test

      - name: Ensure allure-results folder exists
        run: mkdir -p target/allure-results

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-pages-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
